### PR TITLE
Add ISC license

### PR DESCRIPTION
**Pull request by netzhuffle**

### CODE REVIEW

**Comment by dbrgn** [comment]
Fine for me. @rnestler?

(Why not MIT?)

**Comment by dbrgn** [comment]
See also: https://programmers.stackexchange.com/questions/157476/isc-license-advice

**Comment by rnestler** [comment]
Also fine for me. ISC is the default for [npm](https://github.com/npm/npm/blob/master/doc/misc/npm-config.md#init-license), so I think it is common for javascript projects?

**Comment by netzhuffle** [comment]
I chose ISC because it’s shorter than MIT and I’m all in for short and understandable licenses (this has nothing to do with JavaScript). I used MIT before in all my projects, but ISC essentially is the same just with fewer words and—in my opinion—even easier to understand. It’s essentially a two-clause BSD license with unnecessary text removed (and as such it’s e.g. the recommended license by OpenBSD). 

If you prefer to use the MIT license that’s completely fine for me—I just think it’s very important for each of our coredump projects to commit to an open source license which we haven’t done in the past.

**Comment by netzhuffle** [comment]
But I noticed something different (I was to quick and just accepted the GitHub template):

Year should be “2015” or “2015-2016” as the project was first published last year (and not “2016”) and “Coredump Hackerspace” is wrong and should be “coredump” as this is our legal name.

**Comment by dbrgn** [comment]
> and “Coredump Hackerspace” is wrong and should be “coredump” as this is our legal name.

The copyright belongs to the contributors anyways. Swiss law does not allow copyright assignment (only licensing), if I'm not mistaken.

**Comment by netzhuffle** [comment]
In difference to German law, it actually is possible to transfer the copyright in Switzerland, URG Art. 16 Abs. 1. (As a side note: According to URG Art. 17, if you’re writing a computer program as an employee for a company, it’s even automatically transferred.)

But I’m also happy with keeping the copyright as contributors. Would this mean that we need to write our names in the LICENSE file?

**Comment by dbrgn** [comment]
> In difference to German law, it actually is possible to transfer the copyright in Switzerland

I checked again. The Urheberpersönlichkeitsrecht is not transferrable, the Urhebervermögensrecht is. We're talking about the latter here :)

> But I’m also happy with keeping the copyright as contributors. Would this mean that we need to write our namens in the LICENSE file?

No. First of all, it doesn't really matter in the case of a flame bot :wink: And the versioning system allows us to track who wrote which code. So it's not necessary anymore to track that in the copyright header. IANAL.

Just go with something like "Coredump developers and contributors".

**Comment by rnestler** [comment]
I changed some stuff directly in Github. Does everybody agree with that? Also now @The-Compiler should also agree to the license :wink:

**Comment by The-Compiler** [comment]
Consider my typo fix public domain, and any possible future contributions licensed under any FOSS license you see fit :wink:

**Review by netzhuffle — COMMENTED** [review]
LGTM

**Comment by dbrgn** [comment]
+1 from me

**Pull request merged**
