### PR TITLE
Add testimonials

### PR DESCRIPTION
**Pull request by The-Compiler**

### CODE REVIEW

**Comment by rnestler** [comment]
Is Henry also a flame bot? :joy:

**Comment by The-Compiler** [comment]
Nope, it's a human... Guess he failed the turing test then?

**Comment by netzhuffle** [comment]
Actually, it’s the other way around: If you cannot reliable tell who is a bot and who is human, the bot passes the Turing test.

**Review by rnestler — APPROVED** [review]
Looks fine to me.

**Pull request merged**
