### PR TITLE
Add English insults from SoMI

### PR DESCRIPTION
**Pull request by rnestler**

### CODE REVIEW

**Comment by netzhuffle** [comment]
Thanks!

For consistency, could you please use the formatting from the German lines and use real apostrophe signs (’) instead of escaped straight single ticks (\')?

**Comment by rnestler** [comment]
> For consistency, could you please use the formatting from the German lines and use real apostrophe signs (’) instead of escaped straight single ticks (')?

Is there a formatting tool for typescript? I couldn't find one immediately and gave up searching :wink:

**Comment by netzhuffle** [comment]
> Is there a formatting tool for typescript?

Unknown. Honestly, so far I did not edit this yet since it was converted to TypeScript.

**Review by netzhuffle — APPROVED** [review]

**Comment by dbrgn** [comment]
@rnestler https://prettier.io/

**Pull request merged**
